### ISSUE TITLE
multiple "user is editing" cards

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1770] opened 2018-02-19 02:37 UTC
## Issue - Bug

![exco](https://user-images.githubusercontent.com/14892189/36360631-d71ae504-14f3-11e8-9529-e098d9a11442.jpeg)
![product](https://user-images.githubusercontent.com/14892189/36360632-d73e4de6-14f3-11e8-9257-2fdd70b54eb7.jpeg)

### Acceptance Criteria (optional)
A user can:
   - Have a second teammate not generate a number of "Is adding a Task..." cards

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment] 2018-02-19 15:30
I had seen this with @ackernaut too last week after we shipped. I suspect this regression was introduced when refactored to eliminate socketcluster. This will be a fun one to track down!

I suspect (but haven't confirmed) this state is encountered when the following occurs:

1. User A and User B are navigated to the same team dash
2. User A is passive, and is watching the team dash
3. User B clicks a button to add a new card
4. User B then disconnects (e.g. by closing their laptop lid)

**Comment by mattkrick** [comment] 2018-02-19 19:29
i'm betting this has something to do with the unsent message queue that's introduced.
next steps:
- [ ] set up a ping listener on the client that is identical to the pong listener on the server. it looks like we don't detect disconnects until the reconnection occurs.
-[ ] if the above doesn't fix it, then we'll need to investigate the logic implemented by the queue. apollo may not be clearing the queue when it should be.

Estimated effort: 11 points

**Closed** 2018-02-20 05:47 UTC
Labels: bug, groom-ready
