### ISSUE TITLE
"Pointer" Feature During Meetings

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1123] opened 2017-06-27 15:38 UTC
## Issue - Enhancement

While running teammates quickly through your personal Updates during a Check-In meeting, it would be swell if there was a visual indicator of which card the speaker was addressing. Similar to Trello: as the user moves mouse over the board, each card is highlighted light grey. We could do similar light [Parabol color] or a temporary halo border, etc.

**Comment by ackernaut** [comment] 2017-07-25 16:45
This makes me think of cursors in Figma…

**Comment by jordanh** [comment] 2017-07-25 16:48
Duplicate of #656

**Closed by jordanh** 2017-07-25 16:49 UTC
