### ISSUE TITLE
GitHub integration user counts do not increment/decrement when using (Un)Link Me

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1185] opened 2017-08-02 15:44 UTC
## Issue - Bug

Reproduction steps:

1) Sign into Parabol in two windows, with two users (A, B)
2) Create a team, make sure both users are added to the team
3) Add the GitHub integration to the team for both users
4) Have user A user view the integrations window
5) Have user B add two repositories, like so:

![image](https://user-images.githubusercontent.com/103000/28881912-83b435b0-775e-11e7-93f4-ca07eb825fd2.png)

Note user count on user's A screen:

![image](https://user-images.githubusercontent.com/103000/28881946-9e349682-775e-11e7-9b3d-a8d92287784c.png)

6) Remove user B from both GitHub repositories

![image](https://user-images.githubusercontent.com/103000/28881965-abd6b3c4-775e-11e7-8f08-0ecf2668dbb5.png)

Note that user A's view of user count does not change:

![image](https://user-images.githubusercontent.com/103000/28881990-bb04032e-775e-11e7-9452-53d115862c62.png)

This is a low priority fix.

- **OS:** OSX
- **Browser:** Chrome
- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment] 2017-08-02 15:45
I'm guessing this is working as designed, as the user count counts the number of folks with active tokens, not distinct users on repos...

**Comment by jordanh** [comment] 2017-08-02 15:47
Does that mean that:

- `userCount` is really the number of folks who have active auth tokens?
- `integrationCount` is really the number of repos added to a team integration?

**Comment by ackernaut** [comment] 2017-08-02 15:51
Ha! Looks like I need to fix the spacing on those avatars, too.

**Comment by jordanh** [comment] 2017-08-02 16:07
See #1187

**Comment by mattkrick** [comment] 2017-08-02 18:52
your definitions are correct! closing as "working as intended" but if there is any room for improvement lemme know

**Closed by mattkrick** 2017-08-02 18:52 UTC
Labels: bug, low priority
