### ISSUE TITLE
Live Agenda Links

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1079] opened 2017-06-13 23:41 UTC
## Issue - Enhancement

Build live link capability in Agenda items--needn't be full WYSIWYG editing menu; but when a user types a url, it should link out 

Will be particularly useful for future Recurring Agenda Items and future Metrics capabilities.

Related to recent Enhancement request to make a Library Links column for frequent docs #1059

**Comment by ackernaut** [comment] 2017-06-14 00:16
Duplicate of #669

**Closed** 2017-06-20 16:53 UTC
Labels: enhancement
