### ISSUE TITLE
Meeting summary from timeline not rendering correctly

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#3044] opened 2019-07-22 21:24 UTC
## Issue - Bug

[This user](https://app.hubspot.com/contacts/3888472/contact/4804901) reported that their meeting summary appeared to be empty for this meeting: https://action.parabol.co/new-summary/1C48388aMCb

Investigating into the database, all the data is there. Try the query:

```
r.db('actionProduction')
    .table('RetroReflectionGroup')
    .getAll("1C48388aMCb", { index: 'meetingId' })
    .pluck('title', 'id')
    .concatMap( (rg) =>
      r.db('actionProduction')
       .table('RetroReflection')
       .getAll(rg('id'), { index: 'reflectionGroupId' })
       .pluck('content')
       .merge({ groupTitle: rg('title') }) )
       .map( (reflect) => ({
         group: reflect('groupTitle'),
         reflection: r.json(reflect('content'))('blocks').nth(0)('text')
       }))
```

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - Load a  summary link and see their old meeting data

### Support ticket

https://app.hubspot.com/contacts/3888472/ticket/37118157

**Comment by mattkrick** [comment] 2019-07-31 04:21
Working as intended (i love it when i get to say that :smile:)

it's empty because there were no votes cast.

should we include all items, including those without votes?

**Comment by jordanh** [comment] 2019-07-31 13:06
Oh awesome @mattkrick. Changing this to a discussion.

**Comment by jordanh** [comment] 2019-07-31 14:17
I think our design intentions were good: to only include in the summary what was deemed important by the team. I think we're erring on the side of being too prescriptive here (i.e. "flexibility even over prescription"). See also: #2741 (which is a direct ask for this) and #2862 (show all groups in discussion, even those without votes).

I can see going a couple of different ways here:

1. We implement #2741 as written (show everything in the summary) or,
2. We update the summary to include a statement to be more clear on what is being shown and why

I'm in favor of the first option

In any case, I think this issue is now a dupe. Any objection to closing it in favor of #2741?

**Comment by mattkrick** [comment] 2019-07-31 17:54
dupe of #2741

**Closed by mattkrick** 2019-07-31 17:54 UTC
Labels: bug, discussion, user request
