### ISSUE TITLE
Bad column height during vote phase

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#3491] opened 2020-01-17 00:28 UTC
Repro:
- Left column has 7, 3 with 1 line, 2 with 2, 3 with 3
- Right column has 4
- Notice left and right column exceeds the page height, can't scroll all the way to the bottom

AC
- vert height is right

Effort: 11 points

**Comment by jordanh** [comment] 2020-01-28 18:11
Closing this one as a duplicate of #3525

**Closed by jordanh** 2020-01-28 18:11 UTC
Labels: bug
