### ISSUE TITLE
Implement Slack updates for team notifications [WIP]

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2870] opened 2019-05-06 20:26 UTC
TBD based on final designs from #2841 

### Acceptance Criteria
- Can push notifications to Slack per meeting start/end (sync UX) or per phase start/end (async UX)
  - Supports: async phase notifications are optional for any phase timebox, and are controlled by the facilitator in the meeting UI
- TBD team has single, preferred channel or can add/remove multiple channels
- Slack details are accessible from Slack provider card:
  - TBD the details are in a show/hide section, or in a dialog toggled from the more menu

### Estimated Effort
- 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment] 2019-05-28 12:16
Duplicate of #2921 and #2924

**Closed by jordanh** 2019-05-28 12:16 UTC
Labels: enhancement
