### ISSUE TITLE
Exception thrown when re-entering meeting to grouping phase

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2306] opened 2018-08-08 00:56 UTC
## Issue - Bug

Start a meeting with two participants, User A and User B. Let User A become the facilitator. Then:

1. Enter reflections and proceed to Grouping Phase
2. As User A, click on the team name to return to the dashboard
3. As User B, create a new group
4. As User A, re-enter the meeting and observe exception

```
ReflectionCardInFlight.js:68 Uncaught TypeError: Cannot destructure property `initialComponentCoords` of 'undefined' or 'null'.
    at new ReflectionCardInFlight (ReflectionCardInFlight.js:68)
    at constructClassInstance (react-dom.development.js:11333)
    at updateClassComponent (react-dom.development.js:13036)
    at beginWork (react-dom.development.js:13715)
    at performUnitOfWork (react-dom.development.js:15741)
    at workLoop (react-dom.development.js:15780)
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:138)
    at invokeGuardedCallback (react-dom.development.js:187)
    at replayUnitOfWork (react-dom.development.js:15194)
```

- **OS:** macOS
- **Browser:** Chrome
- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
User A can:
   - Exit and re-enter the meeting to the Grouping phase without encountering the exception

**Comment by mattkrick** [comment] 2018-08-08 16:29
dupe of #2259. should be fixed in #2307

**Closed by mattkrick** 2018-08-08 16:29 UTC
Labels: bug
