### ISSUE TITLE
Regression: clients unable to accept invitations [Epic2]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#759] opened 2017-02-27 17:42 UTC
## Issue - Bug

![image](https://cloud.githubusercontent.com/assets/103000/23370658/6622d40c-fce3-11e6-9e76-5c77b3e9317a.png)

Steps to reproduce:

1. Go to Team Settings, invite new team member
2. As new team member, click on invitation link
3. Observe ducks forever

I'm surprised that this wasn't tripped by our unit tests!

- **OS:** OSX
- **Browser:** Chrome

**Comment by mattkrick** [comment] 2017-02-28 05:40
imma need some more details on this one, it works fine on local. it looks like you were doing this on the staging server, correct? have you tried this since fixing babel?

**Comment by jordanh** [comment] 2017-02-28 12:39
Yeah, it's on the staging server. Since this looks like an error field coming back from the backend, I'm guessing this is a migration thing.

I have an idea! Do you want to ping me when you wake up this morning? We can use the new rethinkdb tunnel and debug this one together! It'll be fun.

**Comment by mattkrick** [comment] 2017-03-05 18:23
@jordanh can you give me some new repro steps for this?

**Comment by jordanh** [comment] 2017-03-06 05:35
I am going to retest with Sasha when I get a chance...

**Comment by mattkrick** [comment] 2017-03-10 01:23
Reproduced! I got this when the user exists in auth0, but does not exist in our DB.
This could very well be the case with Sasha as she was an early adopter. Is it possible that she made an account in a pre-database clearing event?

**Comment by mattkrick** [comment] 2017-03-10 01:54
for now, i wrote a fix that creates the user in our DB if they don't already exist in it but they do exist in the auth0 db. If you can reproduce it now, then we got quite the bug on our hands!

**Comment by jordanh** [comment] 2017-03-10 02:59
Looks like we got quite a bug on our hands! Here's the steps I'm going through:

Me:

1. Go to Team Settings, send invitation to `sashajwright@gmail.com`

Her:

1. Click on link in email
2. Log in with email (not Google authentication)
3. See duckies

This is the exception:

```
DEBUG GraphQL Error: [ { TypeError: Cannot read property 'userOrgs' of null
2017-03-10T02:54:57.205873106Z app[web.1]:       at _callee2$ (/app/src/server/graphql/models/TeamMember/teamMemberMutation.js:124:24)
2017-03-10T02:54:57.206200645Z app[web.1]:       at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:63:40)
2017-03-10T02:54:57.206397685Z app[web.1]:       at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:337:22)
2017-03-10T02:54:57.206452663Z app[web.1]:       at Generator.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:96:21)
2017-03-10T02:54:57.206626724Z app[web.1]:       at step (/app/src/server/graphql/models/TeamMember/teamMemberMutation.js:49:191)
2017-03-10T02:54:57.206842047Z app[web.1]:       at /app/src/server/graphql/models/TeamMember/teamMemberMutation.js:49:361
2017-03-10T02:54:57.207779985Z app[web.1]:     message: 'Cannot read property \'userOrgs\' of null',
2017-03-10T02:54:57.207807490Z app[web.1]:     locations: [ [Object] ],
2017-03-10T02:54:57.207819592Z app[web.1]:     path: [ 'acceptInvitation' ] } ]
```

**Comment by mattkrick** [comment] 2017-03-10 03:35
_should_ be fixed on the billing unit tests branch.

**Closed** 2017-03-12 04:30 UTC
Labels: bug, pr review
