### ISSUE TITLE
new cards w/dates in meetings get date-influenced sortOrder

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1306] opened 2017-08-29 19:32 UTC
## Issue - Enhancement

When a card is created in a meeting, its `sortOrder` is set by its date.

This one needs to be scoped.

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tayamueller** [comment] 2018-03-06 21:16
duplicate of #1211

**Closed by tayamueller** 2018-03-06 21:16 UTC
