### ISSUE TITLE
TypeError: Cannot read property 'atlassianAuth' of undefined

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2980] opened 2019-06-25 21:48 UTC
https://sentry.io/organizations/parabol/issues/1085135539/?referrer=github_plugin

```
TypeError: Cannot read property 'atlassianAuth' of undefined
  at c (./src/universal/components/TaskFooterIntegrateMenu.tsx:28:10)
  at Set.forEach (<anonymous>)
  at run (./src/universal/LinearPublishQueue.ts:196:17)
...
(24 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment] 2019-07-02 17:08
AC:
   - Root cause determined and new issue opened or fixed if less than EE

EE:
   - 10.5 points

**Comment by jordanh** [comment] 2019-07-02 17:09
As of today, only 1 user affected on sentry. Marking as low priority for now.

**Comment by jordanh** [comment] 2019-07-02 17:10
@mattkrick sez it's still a critical error if hit so remove low priority. This is starting to point at what low priority means (truly non-critical and truly rare)

**Closed** 2019-07-10 01:51 UTC
Labels: bug
