### ISSUE TITLE
Summary count of new cards created is wrong

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1703] opened 2018-01-31 17:58 UTC
## Issue - Bug

The Summary of new cards created doesn't reflect what happened.

Summary:
![project count bug](https://user-images.githubusercontent.com/14892189/35638657-ab82122c-0685-11e8-9364-4886da1cde81.jpeg)

Actual: [5 new cards created, not counting the 3 pre-pop'd for Onboarding]
![actual](https://user-images.githubusercontent.com/14892189/35638878-5474ce60-0686-11e8-8354-976918e2c1e4.jpeg)

**Comment by jordanh** [comment] 2018-02-14 16:13
During backlog groom, we suspected that this has already been fixed. Let's retest it.

# User Acceptance:
- When Task cards are added during Project Updates that they appear and are counted in the meeting summary
- When Tasks are created elsewhere in the meeting, the same occurs

**Comment by mattkrick** [comment] 2018-02-22 03:50
Could not reproduce, closing & assuming it's fixed!

**Closed by mattkrick** 2018-02-22 03:50 UTC
Labels: bug, groom-ready
