### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#622] opened 2017-01-10 17:18 UTC
## Issue - Enhancement

Users wanna search for stuff: finding stuff in Archives; finding "something" but you can't remember which Team it was for; searching quickly for items inside a crowded dashboard, etc.

**Comment by mattkrick** [comment] 2017-01-10 20:45
duplicate of #500?

**Comment by jordanh** [comment] 2018-02-14 16:31
First step toward this is #1690

**Closed** 2018-02-14 16:31 UTC
