### ISSUE TITLE
Retro cards flash content and placeholder briefly

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2033] opened 2018-04-20 04:49 UTC
## Bug

When I first create a retro card and quickly try to add text:
- there is a brief flash of the text that I’m adding
- then the placeholder reappears
- then I’m editing again, but starting with no text

And the placeholder seems to stutter when creating a card anyway, even if I don’t type text right away.

### Acceptance Criteria
- Users can type text right away without losing text, seeing the placeholder again, and starting over

### Estimated Effort
- 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment] 2018-04-29 15:46
I ran into this bug too when testing a prior PR. @mattkrick said it looked like a draftjs bug. I'm upping the EE.

**Comment by mattkrick** [comment] 2018-04-30 15:08
this is fixed in 1 of the outstanding PRs. this is caused by optimistically creating a card. to fix, i made the card read only until the card returns from the server, so you can see the card was created instantly, but cant do anything for ~300ms

**Closed** 2018-05-02 15:37 UTC
Labels: bug
