### ISSUE TITLE
Implement prompt descriptions

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2703] opened 2019-03-05 20:35 UTC
Implements prompt descriptions as designed in #2634 ([see Figma](https://www.figma.com/file/MZ1A8PG7aOuupJK0cxzEwmMn?node-id=20%3A1239&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#4782470))

### Acceptance Criteria
- Updates existing default templates per final iteration of [Google Sheet](https://docs.google.com/spreadsheets/d/10kog95I4TDJtTWptv9UqhTfnhOkDkmiNFQBGJj_qfss/edit#gid=0)
- Allows users to optionally CRUD a description to any prompt in template editing dialog
- Horizontal alignment (prompts, descriptions, inputs) is maintained (collapses if no descriptions for any prompt)
- Limited to 1 line on mobile, tap down arrow to expand full text for remaining lines

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment] 2019-03-28 00:30
@ackernaut can you shoot me a link to the design showing how to CRUD the description?

**Comment by ackernaut** [comment] 2019-03-28 16:29
@mattkrick working on template editor UI updates now

**Comment by ackernaut** [comment] 2019-03-28 17:34
Also, re: updating existing prompt templates:
- I think I only want to update prompts and add descriptions to Sailboat
- I want to add commas to Start, Stop, Continue template name

**Comment by jordanh** [comment] 2019-04-02 17:12
Dupe of #2765

**Closed** 2019-04-09 16:18 UTC
Labels: enhancement
