### ISSUE TITLE
delete teams

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1058] opened 2017-06-07 17:59 UTC
## Issue - Bug

I see that now when I "Leave Team" the team is deleted from my leftnav column. 

However, 5 old teams (before the update?) remain, although I am no longer a teammate

**Comment by ackernaut** [comment] 2017-06-07 20:05
Yeah, I have this same issue. Is there a way to migrate data and clean up those old teams @mattkrick ?

**Comment by jordanh** [comment] 2017-06-20 17:02
This only applies to old teams. Step 1: let's come up with a query.

**Comment by mattkrick** [comment] 2017-06-20 17:04
Duplicate of #1001

**Closed** 2017-08-25 00:01 UTC
Labels: bug, sprinting
