### ISSUE TITLE
Wrong initial read on trial expiration

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#913] opened 2017-04-13 21:13 UTC
## Bug

Steps to reproduce:

1. Create a new user
2. Complete welcome views
3. See a modal for trial expiration?
4. Go to settings?
5. Hit refresh and it clears up (notice the little exclamation triangle disappears from dash nav)

See:

![screenshot 2017-04-13 16 11 09](https://cloud.githubusercontent.com/assets/307286/25024593/20ac24f6-2064-11e7-948a-4bebd75f5807.png)
![screenshot 2017-04-13 16 11 14](https://cloud.githubusercontent.com/assets/307286/25024594/20ad2450-2064-11e7-86e3-5938cef5404e.png)
![screenshot 2017-04-13 16 13 35](https://cloud.githubusercontent.com/assets/307286/25024603/2a9cc920-2064-11e7-8afe-4632e81bf3c3.png)

**Estimated effort**: 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment] 2017-05-16 23:12
does this still happen for you @ackernaut? i don't think i did anything, but i can't reproduce

**Comment by mattkrick** [comment] 2017-05-17 02:07
closing for now as i believe this is fixed

**Closed by mattkrick** 2017-05-17 02:07 UTC
Labels: bug

**Comment by ackernaut** [comment] 2017-05-17 15:35
It looks this was fixed on staging @mattkrick 👍

**Comment by ackernaut** [comment] 2017-06-09 20:25
This is happening for me (again) locally. Strange!

**Comment by mattkrick** [comment] 2017-06-09 20:25
Is this for an account that does _not_ exist in auth0?

**Comment by ackernaut** [comment] 2017-06-09 20:27
Yeah, it _should_ be a new user. (I’m using the name**+stuff**@domain.co trick)
