### ISSUE TITLE
search function

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#500] opened 2016-11-07 16:05 UTC
## Issue - Enhancement

In the distant future, a search box to pop up the card you're thinking of would be amazing.

**Comment by jordanh** [comment] 2016-11-07 16:09
Search could be a major undertaking if we let it be. I've often wondered if there isn't a "minimum viable client-side search" we could implement – in fact, more like a filter than a search.

Job story:

When I suspect there is a card containing a keyword and I don't want to scroll and scan for it, I want to type that keyword(s) in the box and watch the card lists filter themselves, so that I can quickly find what I'm looking for.

@tayamueller would this take a step toward what you're trying to accomplish?

Others, would this be useful?

**Comment by jordanh** [comment] 2016-11-07 16:09
(also, this is a very apt 500th issue)

**Comment by mattkrick** [comment] 2016-11-07 18:47
ctrl+f? anyone? bueller?

the reason for a search is that not all of the content is rendered on the screen. If there is content not rendered on the screen, then it's because we've introduced some sort of pagination. If we have to paginate the things you're currently working on, then you're doing it wrong. My pessimistic, engineery, no-mo-features $0.02 :smile:

**Comment by jordanh** [comment] 2018-02-14 16:30
Duplicate of #622

**Closed by jordanh** 2018-02-14 16:30 UTC
Labels: enhancement
