### ISSUE TITLE
Group avatars per repo integration

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1186] opened 2017-08-02 15:53 UTC
## UI Bug

Multiple integrated users per repo need to be grouped, and then can flex with space around. Consider max width on the repo name block.

See screenshots from #1185 

**Estimated effort**: 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment] 2017-08-02 16:07
Duplicate of #1187

**Closed by jordanh** 2017-08-02 16:07 UTC
Labels: bug
