### ISSUE TITLE
New Sign in/up page design

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1654] opened 2018-01-17 16:29 UTC
## Issue - Enhancement

We need a design for our new sign in/up page!

### Acceptance Criteria (optional)
Users can:
   - Do all the stuff in https://github.com/ParabolInc/action/issues/1618
   ... with the design result of this story
  - Wireframes / IA delivered in Figma

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

----

[See the wireframes](https://www.figma.com/file/dlFsGHNy7TclcNQDaacFP0pR/Signin-Signup)

**Comment by jordanh** [comment] 2018-01-25 20:42
See: https://github.com/auth0-samples/auth0-react-samples/tree/master/01-Login

**Comment by jordanh** [comment] 2018-01-29 17:29
Dupe of #1618

**Comment by dan-f** [comment] 2018-01-30 20:50
Updated the top comment with [wireframes in Figma](https://www.figma.com/file/dlFsGHNy7TclcNQDaacFP0pR/Signin-Signup). I focused mostly on getting the IA/workflows fleshed out. Not too confident in my visual design chops at the moment 😅 

Hoping for feedback/review on:
- IA/Workflow/states
- Layout
- Anything else, tbh!

@ackernaut I believe this is ready for your review!

**Comment by ackernaut** [comment] 2018-01-30 23:16
@dan-f in my queue! :)

**Closed** 2018-02-16 18:30 UTC
Labels: design, groom-ready
