### ISSUE TITLE
Immortal agenda items

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1158] opened 2017-07-21 01:44 UTC
## Issue - Bug

After ending our Exco meeting, two agenda items appear to be immortal: 

![image](https://user-images.githubusercontent.com/103000/28445754-46c72802-6d7b-11e7-8285-4c85cdac009f.png)

These top two items were not wiped after our meeting completed.

**Comment by jordanh** [comment] 2017-08-04 02:56
More fun data! Note below agenda item didn't get crossed off as we passed it.

![image](https://user-images.githubusercontent.com/103000/28947621-b46ddb0e-7865-11e7-9e17-4577337b87a5.png)

![image](https://user-images.githubusercontent.com/103000/28947770-97671d6c-7866-11e7-83ee-eb0507e44f23.png)

Possible repro steps:

1. Make `talent` first agenda item
2. Add a bunch of other agenda items
3. Before processing agenda, drag `talent` agenda item further down in the list
4. Process agenda, including `talent`
5. Try to observe bug

**Comment by mattkrick** [comment] 2017-08-24 22:06
the query that would cause this is here: 
```
r.table('AgendaItem')
          .getAll(teamId, {index: 'teamId'})
          .filter({isActive: true})
          .orderBy('sortOrder')
          .nth(facilitatorPhaseItem - 1)
          .update({isComplete: true})
```
closing since I can't reproduce this. 
if it happens again, grab the Team doc from the DB & any server logs.
In the meantime, I'll naively assume that switching to events subs will fix this.

**Closed by mattkrick** 2017-08-24 22:06 UTC
Labels: bug, can't reproduce
