### ISSUE TITLE
What's changed since our last meeting?

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1210] opened 2017-08-03 01:56 UTC
## Issue - Enhancement

Several of our users do daily or twice-weekly check-ins rather than weekly. (the greater the pace of change & chaos, the more frequently a team needs to re-prioritize))

Recommended copy change during Solo Updates: "**What's changed since our last meeting?**"

[current: "What's happened since last week?"]

**Comment by ackernaut** [comment] 2017-08-03 15:38
+1

**Comment by mattkrick** [comment] 2017-08-15 16:32
duplicate of #1069

**Closed by mattkrick** 2017-08-15 16:32 UTC
Labels: enhancement
