### ISSUE TITLE
Refactor actions as privately-labelled projects

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#842] opened 2017-03-21 21:01 UTC
## Issue - Enhancement

We've got enough data now to conclude that private actions are confusing. Let's:

- [x] Add labels/tags to the Project schema
- [x] Expose these labels as a design element on cards
   - When a user types `#private` it renders a span element and adds the label to the project and styles the project card with a yellow background (the current Action card styles).
   - When a user clicks the `x` delete handle of the span element, the element is deleted from the content and the label is removed – transforming the card back into a regular project
- [x] Write a migration to transform existing actions to privately-labelled projects by appending `#private` to end of project content and applying private label to schema
- [x] Update team dashboard default query to show all projects and a user's private projects
- [x] Remove actions list from **My Dashboard**
- [x] Update meeting processing phase copy to reflect these changes
- [ ] During the Agenda phase, users can add a Project or a Private Project. When they choose Private Project, the content area cursor focuses in front of a space and the label ` #private`. This will keep the label at the end of the content string by default unless the user changes it.
- [ ] Extra credit: `shift + click` on the `[+]` in Dash views adds a #private project. (The cursor focuses in front of a space and the label ` #private`.)

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment] 2017-04-06 22:27
Gory detail questions:
- i type `#` in a project and it offers tag dropdowns (private, stuck, etc.). Does it pull in tags from 3rd party services? 
- i select `#private`. does it stay like then while editing (since we're in markdown) or does it transform into a button with an X while in markdown?
- when it's transformed into a button, does it lose the `#`?
- do we need the `#` at all?

**Comment by ackernaut** [comment] 2017-04-06 23:20
My current thoughts:

1. There is a difference between Parabol tags and 3rd party tags. We use our tags for filtering, and they can be anywhere in the content. 3rd party tags are extra “card back” meta info.
2. It stays `#private` while editing. If you create it from `control + click` the Add on a column, or Add a Private Project in Agenda, you autofocus the cursor at the beginning of pre-populated content which is a space and `#private`. Transforms to a tag after markdown renders.
3. Keep the `#` in the little tag button.
4. Yes, I like it and it is the trigger for the autocomplete.
5. Hmm, not within the cards.

I could be wrong:

1. We may want to filter by 3rd party tags and/or map those tags to our tags. If we map, I say we just stick them on the end of the content and then sync. Example: GH issue has #designing we add #designing at the end of the content and then we sync.
2. I think we should be strict about markdown editing vs rendered superpowers (so do not want to say I'm wrong here, haha).
3. Um, not wrong here either!
4. Not wrong here!
5. I think we could have a UI when we overhaul the dashboard (super search, filtering, etc.) where tags show up in different places (active filter tags in the results heading, etc.) and perhaps DnD would be useful for some Pro™ move.
6. I could be very wrong about 1-5.

In the future: I want to be able to create a tag by starting to type `#` but it should start to autocomplete so we don’t create too many variants. I also want other superpowers like #861 .

Also, I could do without the little X to remove tags inside the content for now, but perhaps we can still style them as a little tag when markdown is render. The only way to remove would be to edit the content and yank the `#string`.

My 2 cents…

**Comment by mattkrick** [comment] 2017-04-07 02:06
I have strong feelings about calling this `tags` instead of labels.
- everyone else calls this tags
- tags is shorter
- the term `label` is already used a bunch in our repo (HTML elements, titles, etc.) Doesn't mean we can't call it a label in the copy, but internally if i have to do a big refactor, it's always nice to be able to do a search all & minimize the number of false flags (like when we had 3 or 4 entities called notifications 😝 )

**Comment by mattkrick** [comment] 2017-04-07 02:23
another note: i'd like to get rid of `status` and `isArchived` in favor of eg `{tags: ['done', 'archived']}`.

also, now is the time to discuss custom columns (eg do we let them create an `inbox` column?) and column naming (eg can they rename `future` to `backlog`?) doesn't need to be on this issue, but this same migration & PR would be good.

**Comment by ackernaut** [comment] 2017-04-07 02:38
1. Yeah, I think `tags` makes sense (opposed to `labels`) and we can refactor the existing `Tag` to something else. Good point!!
2. I like that columns could have their respective `tags` with superpowers.

So let me think out loud:

If we define the columns at first (by design, we still just have Future/Stuck/Active/Done) then users can DnD or write the tag in the content #done #stuck etc.

If they type #archive it goes to the archive. Is there any other way it could go to the archive? If they are #done at the end of a meeting then they get #archive. I think we leave any column tags in case they un-archive, then it goes back to where it was. (So #future #archive goes back to #future.)

My only thought is that my dragging a card from one column to the other we yank (as an example) #future and add #active at the end of the content in the process?

If we did decide to allow additional columns and/or renaming/reordering then I would think that those columns would get the same treatment, a #tag with the #column name would exist when it is in that column.

Then we can get rid of that part of the menu. And now all that is left is @assigning :) haha.

**Comment by ackernaut** [comment] 2017-04-07 02:40
Oh, I was thinking we could have an archive drop zone on the dash.

So, four columns and then in a space above the columns where the archive link/button/control is that reasonably sized area turns into dotted drop zone indicating the user could drop it there too (opposed to just switching columns) which automatically appends #archive to the existing card content.

**Comment by ackernaut** [comment] 2017-04-07 02:40
Oh, I was thinking we could have an archive drop zone on the dash.

So, four columns and then in a space above the columns where the archive link/button/control is that reasonably sized area turns into dotted drop zone indicating the user could drop it there too (opposed to just switching columns) which automatically appends #archive to the existing card content.

**Comment by mattkrick** [comment] 2017-04-07 05:10
can tags be mutually exclusive? for example, you can't be both active & stuck. if no, i guess that means we should keep status separate. can't decide...

**Comment by ackernaut** [comment] 2017-04-07 15:22
Good point, unless we come up with a couple of rules:

1. If a column superpower tag existed in the content and a second is added during a content update, the first one is removed when finishing the update to the content. (This might look funny if it is in the middle of a phrase or statement “PR merged, #stuck by package update” `->` “PR merged, by package update #active” (if it were a simple DnD from Stuck to Active—I imagine if one typed `#active` that person would also scrub the content about why it was `#stuck`.
2. If new content is entered and introduces more than one column tag (and there was not any in the content before hand) then the last one entered wins and the other is scrubbed.

Sounds kind of nuanced and I’m not sure it’s the best UX. I think we can start by leaving it as at `status` with the optional menu updates (opposed to DnD) unless we learn more about our #tag system.

**Comment by mattkrick** [comment] 2017-04-07 18:52
yeah, for that reason i think using hashtags in sentences isn't great, because the same could apply to any tag, right? If i have a `Designing` tag and a `Needs Review` tag in GitHub, then if i try to be cute & write `I am #Designing this right now` when someone changes it on GitHub it'll change to `I am #NeedsReview this right now`. That ain't good. It's my opinion that the tag & the content should be distinct. You can mix em on twitter because a tweet is immutable. In our system, tags will change will content stays the same, which means we should keep em separate.

**Comment by ackernaut** [comment] 2017-04-10 15:35
Yeah, my thought is that inline tags would work if we kept our tags separate from integrated tags. If we map and sync, then I agree, probably not doable.

Lazy example:

This is the **#design** card content.
GitHub issue 376 (**enhancement**)

Vs:

This is the card content.
GitHub issues 376 (**enhancement** [maps to] **design**)

**Comment by mattkrick** [comment] 2017-04-11 15:43
let's talk taxonomy. do we still like "project"? Personally, i think project sounds a bit too grandiose & would prefer "task", and then many tasks could roll up into 1 project, etc etc. but i'm cool with whatever you guys decide

**Comment by mattkrick** [comment] 2017-04-11 18:38
I'm a bit unclear on the styling of tags.

The above states this:
> When a user types #private it renders a span element and adds the label to the project and styles the project card with a yellow background (the current Action card styles).

> When a user clicks the x delete handle of the span element, the element is deleted from the content and the label is removed – transforming the card back into a regular project

But as previously discussed in slack, we were talking about only rendering that in markdown & while editing, it just looks #normal.
So, to confirm: the `X` only appears in rendered markdown, but to get to editable text, you still just click the div. BUT, if you click an `X` inside that div, it doesn't make it editable, rather it just removes the tag. Is this correct?

From a UX perspective, I think this is gonna get frustrating. We encourage people to click anywhere in the div to edit. We also encourage them to click anywhere on the card to drag. I foresee many people clicking "anywhere" that happens to be on an `X` and now they accidentally removed a tag & have no idea what tag it was or how to bring it back. Thoughts? @ackernaut @jordanh

**Comment by mattkrick** [comment] 2017-04-12 01:11
> During the Agenda phase, users can add a Project or a Private Project. When they choose Private Project, the content area cursor focuses in front of a space and the label #private. This will keep the label at the end of the content string by default unless the user changes it.

This will nullify our "delete the card if it is pristine & empty" policy since the card will no longer be pristine. We can add some `if (!content || content === '#private')` logic, or we can wait to add the #private until they blur it. your call

**Comment by ackernaut** [comment] 2017-04-12 01:36
So my quick thoughts @mattkrick :

1. Taxonomy – For some reason I keep coming back to: Teams have Epics have Projects have Tasks. I think this _seems_ logical to me, but I’m not comfortable wanting to make it that complex until I see the value (user jobs to be done; software should be fun; simple design is hard; priority, clarity, sharing). I do like making a list of tasks to check off to finish something. Does Action have to be that granular? If we don’t go granular then I think that we go opinionated on the naming. I think “projects” is still safe although some things are bigger (portions of an Epic) are smaller (do that tiny, quick task). What if we go back to “outcomes”? It’s different; too much of a semantic curve?

2. I think I want to forgo the the “x to remove” on the tags for now. I think we can try to render them a little differently, but the only way to remove them is to edit the markdown (unless there is some superpower that removes that I am not remembering at the moment). Later we can see if there is any value in that UI to remove (and if we can get past anti-pattern UX cases that you are describing).

3. A few ideas about private outcomes during a meeting: I like the `if (!content }} content === '#private') because it can teach the magic of the tag. Also, I am assuming that private cards are visible during the meeting when they are created and in the summary. Then after that meeting is over they are only visible to the user (dashboard).

**Comment by mattkrick** [comment] 2017-04-12 03:05
i'm gonna punt on the adding `#private` to new cards, at least for now. here's why:
- the value add is LOW (2, count them, 2 keystrokes it saves. `#` + `Tab`)
- excluding it makes the product so simple: just hit 'p'!
- managing caret position is a pain. managing caret positions across browsers/devices is hell. there will be bugs.
- we'll have to rewrite our entire delete pristine card logic.

imagine if gmail had a button that said "send to a gmail address" and all it did was put `@gmail.com` at the end of the `To` input. would you click it? or would you just click the input, type the first 2 letters of the recipient's address, and hit tab to autocomplete?

**Comment by ackernaut** [comment] 2017-04-12 14:14
Sounds good to me. Autocomplete makes a big difference here. We should probably just simplify the create card design to a large `+` icon.

I think at some point it would be nice to have a evergreen doc listing features, shortcuts, and pro tips for the UX/UI where users can learn this stuff. We can send out an email and/or blog post when we add new bells and whistles. I think this would be a good example of that.

**Closed** 2017-05-09 15:50 UTC
Labels: enhancement
