### ISSUE TITLE
bigify avatars

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#320] opened 2016-10-04 14:31 UTC
## Issue - Enhancement

MORE BIGERRRRR AVATARRRRZ

**Comment by ackernaut** [comment] 2016-10-12 14:40
I increased the size of the avatars and accompanying text labels at a breakpoint. Nothing dramatic, but we can close this if ya like.

**Comment by jordanh** [comment] 2016-11-08 23:20
Duplicate of #239.

**Closed by jordanh** 2016-11-08 23:20 UTC
Labels: duplicate, enhancement
