### ISSUE TITLE
Capturing Emails

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#802] opened 2017-03-13 03:34 UTC
## Issue - Enhancement

Connect MailChimp to ensure capture of all Action user signup emails

**Comment by ndey96** [comment] 2017-03-13 03:54
@jordanh Do you think this would be a good candidate for the internship epic?

**Comment by jordanh** [comment] 2017-03-13 12:32
@ndey96 we've got this one! It can be done through marketing automation vs. code.

**Comment by jordanh** [comment] 2017-03-13 12:32
@tayamueller do you want these emails to be captured as a separate list in Mailchimp? If so, what would you want this list called?

**Comment by tayamueller** [comment] 2017-03-15 16:46
"Active Users"...?

**Comment by jordanh** [comment] 2017-04-18 16:26
Duplicate of #854

**Closed** 2017-04-18 16:27 UTC
