### ISSUE TITLE
Exception on demo reflection deletion

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2633] opened 2019-02-07 21:35 UTC
## Issue - Bug

Was standing over the shoulder of a techstars member who was demoing our product. Noticed this bug:

1. Go to: https://action.parabol.co/retrospective-demo
2. Enter a few reflections
3. Delete one

- **OS:** macOS
- **Browser:** Chrome
- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - Delete reflections from the demo

**Comment by mattkrick** [comment] 2019-02-08 01:14
dupe of #2528

**Closed** 2019-02-08 16:28 UTC
Labels: emergency 🚨, pr review
