### ISSUE TITLE
Error: Team already joined

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2854] opened 2019-04-30 22:47 UTC
https://sentry.io/organizations/parabol/issues/885090909/?project=107196&referrer=github_plugin

```
Error: Team already joined
  File "app:///graphql/mutations/acceptTeamInvitation.ts", line 75, in _default.resolve
    return standardError(new Error('Team already joined'), {userId: viewerId})

Error: Team already joined
```

Working as intended, but probably room for a better UX.

Dude is like where tf is my meeting, oh yeah, lemme check my email. click link. then click team dash, then click into meeting.

instead, maybe redirect direct to meeting?

AC
- [ ] don't flag as error

effort: 10.5

**Comment by jordanh** [comment] 2019-06-04 17:27
Scrubbed. Added labels.

**Comment by jordanh** [comment] 2019-06-04 17:28
I think redirect to active meeting is definitely the right thing to do here. In some ways, I think this is duplicate of #2914, right?

**Comment by mattkrick** [comment] 2019-06-10 14:38
i think the way forward would be to stop sending this one to sentry. folks are gonna revisit that invite link, we can't stop em, and it's not an error

**Comment by mattkrick** [comment] 2019-06-25 21:04
path forward is clear, prioritizing

**Closed** 2019-06-26 21:45 UTC
Labels: enhancement
