### ISSUE TITLE
Implements timer design [WIP]

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2871] opened 2019-05-06 20:47 UTC
TBD based on designs from #2804

### Acceptance Criteria
- A control for the timer is in the bottom bar for the facilitator. This location can probably persist in the future as video controls will probably be inline with the avatars. If necessary, it could be moved to the same location as the timer/timebox display location or in a more menu.
- TBD the timer is:
  - a minimal design with smart defaults (could be per team avg. or phase UX) for start/add (eg. tap to start 2 mins, tap to add 1 min)
  - a set of sensible options (start 2, 3, 5, 10 / add 1, 2, 3, 5)
  - a 00:02± control for custom
- The timer is scoped per stage (1 phase has 1 or many stages; stages being rounds for check-in, updates, discuss, agenda) — moving forward a phase or stage clears/stops the timer
- TBD the timer displays to participants:
  - in the top bar by the phase name (heading) — could get crowded on mobile
  - in a styled snackbar floating above the bottom controls or viewport whichever is there, could get crowded on mobile with lots of controls located at the bottom
- TBD if we only have 1 Retro that implicitly handles both async/sync UX
  - the timer could be 1 mode, whereas a date timebox could be the other mode. They could both be configured in the same location (eg. bottom bar, facilitator) and display in the same location (eg. top bar, participants)
  
### Estimated Effort
- 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment] 2019-05-07 22:40
Are the countdown timer values stored (persisted) on the team meeting configuration? For example, if I configure my timers for our teams retro, then run another retro in the future, are the last timer values used set per phase?

Or, is this out of scope for the first pass? (my vote would be out of scope)

**Comment by ackernaut** [comment] 2019-05-07 22:50
Both of the timer concepts proposed offer suggested time values. Matt did mention that we could start to make those suggested times based on team behaviors. I suppose that could be based on team stage/phase duration averages, or even choices from the default options (team always chooses 5 minutes per agenda topic).

**Comment by tayamueller** [comment] 2019-05-10 19:10
feedback from [this distributed team leader](https://app.hubspot.com/contacts/3888472/contact/3254151/):

> Possibility to start a timer directly on parabol: usually for the idea generation part, I'm putting a 7-8min timer on my phone right now

**Comment by jordanh** [comment] 2019-05-28 12:15
Duplicate of #2922 and #2923

**Comment by jordanh** [comment] 2019-05-28 12:16
Duplicate of #2922 and #2924

**Closed by jordanh** 2019-05-28 12:15 UTC
Labels: enhancement
