### ISSUE TITLE
New teammate first destination (Team vs My Dashboard vs Meeting)

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#2861] opened 2019-05-01 18:17 UTC
> When I get an invite to join Parabol for the first time, it's confusing to land on My Dashboard Timeline, which is blank. [it took her a while, but...] Once I found my Team's dashboard I had a lot more context."

### Acceptance Criteria (optional)
Per [comment below](https://github.com/ParabolInc/action/issues/2861#issuecomment-499678615):
- [ ] Decide to send the new user who accepts a team invite to the team dash, or keep sending them to the timeline

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment] 2019-05-01 20:53
Was the timeline literally blank? They didn’t see something like this?
![Screenshot 2019-05-01 15 53 00](https://user-images.githubusercontent.com/307286/57042061-49da1a00-6c29-11e9-8ab7-6821cd6a919c.png)

**Comment by jordanh** [comment] 2019-05-14 15:33
Making this a discussion and removing from Sprint board until it has AC and EE. What are the proposed next steps. Or, are we just going to let this issue hang out so we hear the number of times we hear this from users?

**Comment by ackernaut** [comment] 2019-05-24 17:40
By design, if the user accepts an invite they are redirected to either the active meeting for that team, or to the team’s dashboard. So there may have been a confusing move by the user (they signed up before accepting an invite and saw this) or a bug in the invite process. In the future, when multiple teams can be running, we will send them to the recently started meeting, or maybe to the multi-meeting lobby (if long-standing meeting(s) are active) or team dash (whatever becomes a thing once we learn).

**Comment by ackernaut** [comment] 2019-06-06 21:41
This is what I’m seeing locally today (working on #2943):

If the team does not have an active meeting…
- A new user, accepting via the team invite email, will land on the timeline
- An existing user, accepting via the team invite email, will land on the team’s dashboard

I think this may have been intentional when we designed the timeline. Do we want to keep it this way? I can see why a user may say “where’s my team?” but if the team is relatively new and not meeting there may be little context on the team dash, too. I wonder if the timeline should have a “You joined Team ABC” card above the “You joined Parabol” card on the timeline.

Updating the AC and EE for a decision. I’m leaning toward sending the new user to the team dash when they accept a team invite unless there is an active meeting, then they land there.

**Comment by ackernaut** [comment] 2019-06-28 19:37
From another user via email:
>I really struggled with seeing the dashboard vs the specific meeting I was in. I was trying to figure out if my team had gotten in and wanted to send invites to the platform and got fairly lost.

**Comment by jordanh** [comment] 2019-07-09 17:05
Resolved by #2994

**Closed by jordanh** 2019-07-09 17:05 UTC
Labels: enhancement, user request
