### ISSUE TITLE
TypeError: Cannot read property 'getIn' of undefined

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1317] opened 2017-09-01 03:41 UTC
https://sentry.io/parabol/action-production/issues/340877351/

```
TypeError: Cannot read property 'getIn' of undefined
  at method (../node_modules/draft-js/lib/editOnInput.js:89)
  at func (../node_modules/draft-js/lib/DraftEditor.react.js:147)
  at invokeGuardedCallback (../node_modules/react-dom/lib/ReactErrorUtils.js:26)
  at executeDispatch (../node_modules/react-dom/lib/EventPluginUtils.js:85)
  at executeDispatchesInOrder (../node_modules/react-dom/lib/EventPluginUtils.js:108)
...
(13 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment] 2017-09-01 03:43
From user:

> Hi Jordan! Just found a bug on Parabol. Was trying to add a card on my dashboard. When I went to type it in, the text didn't show up.

My response:

> Whoa. That is really interesting! Thank you so much for reporting.
> 
> May I verify the steps that produced this bug?
> 
> 1. You hit the plus button to create a new Card
> 2. You tried to type text on the Card, but the text did not show up
> 
> If you create a second card, did it still happen? If you reload the page, does it still happen?
> 

Her response:

> Yes, correct on the steps. I tried creating a second card and it wouldn't let me. I also tried refreshing, opened a new card and the same things happened.

Is this us, or draftjs?

**Comment by mattkrick** [comment] 2017-09-01 15:30
oh i'm glad we got backstory on this one, i was checking it out when sentry sent it and was totally confused.
It could be related to https://github.com/facebook/draft-js/issues/473
it came from /me, i tried reproducing with 1 team and many teams, i can't reproduce on production or local.
The problem is likely not ours, my hunch is that it's draft getting caught in a weird render cycle with react where it's finding the wrong editor on the page & when it looks up the key in that editor, it isn't found.
if that's the case, it may be possible that moving to react v16 could fix this since it has a different render algo.
just spitballing here... maybe since our `onChange` callback does a lot of stuff & queues up a lot of rerenders, on a slow machine react could be breaking those changes apart & we'd be ending up with an intermediary state if it can't do it all within the time allotted.

**Comment by jordanh** [comment] 2017-09-01 18:37
Turns out that this is happening with the Safari browser. Reproducible on mobile and on OSX desktop.

**Comment by ackernaut** [comment] 2017-09-01 18:46
@jordanh good find, we should probably start doing the UI walkthrough in Chrome, Safari and Firefox (a bit better than just looking at Chrome, right?).

**Comment by mattkrick** [comment] 2017-09-01 20:04
here's the issue in draft, verified that it's the parent drag container that's borking the whole thing: https://github.com/facebook/draft-js/issues/1326

i could try to tackle this one, or we could let the facebook folks + community go after it. the issue has been open for 3 weeks

**Comment by jordanh** [comment] 2017-09-01 20:33
What do we say to let this hang out for another week or so and see if they tackle it?

**Comment by mattkrick** [comment] 2017-09-01 20:44
Sounds good to me

**Comment by mattkrick** [comment] 2017-09-01 21:41
Curiosity got the best of me. 🙈 
See https://github.com/facebook/draft-js/pull/1356
I'll change our dep to my branch & we can push to prod today.

**Closed** 2017-09-03 03:52 UTC
Labels: bug, pr review
