### ISSUE TITLE
Option for Stuck items to "Move to Agenda"

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1287] opened 2017-08-22 01:20 UTC
## Issue - Enhancement

Sometimes, a Stuck item needs to be escalated to a Team Agenda Queue. 

Currently the steps are:
-(original card is in Stuck)
-related Agenda item is typed in Queue
-Agenda item is processed in Meeting
-(no access to original card) new card is typed
-redundant cards now exist

Would be nice to be able to simply "Move to Agenda" from inside the bottom right menu options:
-(original card is in Stuck)
-user selects "Move to Agenda" from menu options
-card remains in Stuck column (perhaps highlighted light purple? some other visual signifier?)
-first line of card text is also added to Agenda Queue
-(if Agenda item is deleted, original card reverts to normal protocols)
-when Agenda item is processed in Meeting; original card is visible as a pre-populated card
-card (with any new edits & column classification; moved to Active, etc.) reverts to normal protocols

**Comment by ackernaut** [comment] 2017-08-22 16:15
Duplicate of #1083

**Closed** 2018-03-06 22:54 UTC
Labels: enhancement
