### ISSUE TITLE
continuing links with spaces creates two multiple elements [draftjs]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1093] opened 2017-06-20 03:52 UTC
## Issue - Bug

Steps to reproduce:
1. Create a new Project card
2. Type `ThisIsALink`, then highlight the text and press ⌘-k/ctrl-k to create a link via the modal
3. In the modal type `http://parabol.co` and 
4. Position the editing cursor between each camel-cased word and insert spaces such that it becomes `This Is A Link`
5. Note that each word is now its own separate link and that the links cannot be removed by highlighting all of the words and clicking `Remove` on the modal

- **OS:** OSX 
- **Browser:** Chrome

**Comment by mattkrick** [comment] 2017-06-20 18:24
I'll flag this as a duplicate of #1094 because the root cause & solution are the same.
How Draft-js works is by assigning an entity per-character, not per-word. so, that means each character is its own separate link to the url.

**Closed by mattkrick** 2017-06-20 18:24 UTC
Labels: bug
