### ISSUE TITLE
Error when joining retro meeting after starting

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2259] opened 2018-07-12 17:43 UTC
## Issue - Bug

Reproduction steps (on current staging at v2.5.0):

- Log in as 2 players on the same team (use incognito or 2nd browser for player 2)
- Player 1 starts a retro meeting
- Player 1 advances through check-in
- Player 1 writes a bunch of reflections and advances to group
- Player 2 joins when player 1 is at group phase
- See errors? Seems if you refresh the URL it will load correctly.

```
TypeError: Cannot read property 'phaseTypes' of undefined
    at e (NewMeetingSidebarPhaseList.js:41)
```

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
- Teammates can join late during any retro phase

**Comment by mattkrick** [comment] 2018-08-01 00:43
cannot reproduce, can you try it again? 
perhaps it got fixed with something else?

**Comment by ackernaut** [comment] 2018-08-01 13:54
I just did the steps on staging at v2.7.0:

- 2 players signed in
- player 1 starts the retro (while player 2 is on My Dashboard)
- player 1 advances to reflect, writes 4 reflections
- player 1 advances to group, groups 2 cards to 1 grouping
- player 2 joins the retro
- >An error has occurred! We’ll alert the developers. Try refreshing the page

Maybe it was fixed on something since v2.7.0. Will try the steps locally and comment.

**Comment by ackernaut** [comment] 2018-08-01 13:59
Ok, I just tried the steps again on `master` (latest including Vote UI updates). I got the same results. Here’s the main action to take: If player 1 advances to Group and has not grouped any cards, then when player 2 joins from My Dashboard there is no error. If player 1 has grouped at least 2 cards, then player 2 gets the error.

**Comment by mattkrick** [comment] 2018-08-08 00:36
great bug!
so the root problem is we ignored `endDrag` events if the user isn't in the meeting.
we do this because if I'm in retro for team A & i get an event for the retro on team B, i should just ignore that.

my knee jerk reaction tells me that we should include the same logic for start & update drag events. however, events may be replayed, so let's say I send off a "createTask" mutation, get a "startDrag" event that i want to ignore. when that "createTask" mutation returns, the "startDrag" event will get replayed, and if i am now in the meeting, then it will no longer be ignored.

I _think_ that's OK, because that means the updates & end drag event would also be queued, the handling should be fine.

An edge case is i ignore the start event, then join the meeting, then get an end event. we'll need to make sure the end event can reach convergence without the start event. I _think_ it can.

**Closed** 2018-08-08 16:33 UTC
Labels: bug, pr review
