### ISSUE TITLE
extendedTrial doesn't remove old stripe subscription

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1292] opened 2017-08-23 18:40 UTC
## Issue - Bug

When a user's trial is extended, the current implementation of the `extendedTrial` mutation does not remove the old Stripe subscription. This is a real bummer for users who's trial has elapsed as any subscriptions which have become active will invoice and charge the customer unexpectedly.

To fix this, we'll need to remove any active sub_ records from the customer on stripe before adding the new trial subscription.

- **OS:** Linux
- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment] 2017-08-24 18:31
dupe of #1119, which is on deck for 6.5

**Closed by mattkrick** 2017-08-24 18:31 UTC
Labels: bug

**Comment by mattkrick** [comment] 2017-08-24 22:49
ok, here's the assumed business loigc:

User signs up on day 0.
User Adds CC on day 15
User is billed on day 61 for days 61 - 90 ($5)
We extend trial on day 75
We charge for 15 days ($2.50)

User signs up on day 0.
User Adds CC on day 15
User is billed on day 61 for days 61 - 90 ($5)
User adds a new member on day 62
We extend trial on day 75
We charge for for 15 days ($2.50) ***and ignore the adjustments***

To be clear: THIS IS A HACK.
In the future, if giving people a free month is gonna be a thing, let's create a sprint around that. Stripe has coupons & we can do it right. Putting them back on a trial is not ideal & there are guaranteed to be more bugs to arise.
