### ISSUE TITLE
Cannot replace avatar [Epic 2]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#754] opened 2017-02-27 14:13 UTC
## Issue - Bug

With v0.16.0 on staging, I'm unable to replace user avatar image:

![gif](http://g.recordit.co/HFAnSly3Cy.gif)

- **OS:** OSX
- **Browser:** Chrome

**Comment by jordanh** [comment] 2017-03-02 21:37
This still isn't working on staging for me.

**Comment by mattkrick** [comment] 2017-03-02 21:50
Oh well that's all kinds of weird because it worked on staging for me! Can
you give me a full repro list?

**Comment by jordanh** [comment] 2017-03-02 21:52
For me, it's:

1) Log in as me via Google
2) Set avatar image, close modal
4) Set new avatar image, observe failure

There is also a server exception reported to Sentry (#772).

**Comment by mattkrick** [comment] 2017-03-05 18:24
if this has the same root cause as #772, then it is fixed in the dnd branch, will add a human test in that PR

**Closed** 2017-03-05 23:57 UTC
Labels: bug
