### ISSUE TITLE
Square avatars are square (with rounded styling)

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#608] opened 2017-01-05 18:40 UTC
TA’s newer message on spec:

👾 

We want avatars to be square at all times. And currently, we prefer that they be rounded using CSS to a circle shape. So there is a quick way and a more involved way to do this:

### Quick Win™

- See: #678
- [ ] Quick Win = DONE

### The Right Way™

- See: #679
- [ ] The Right Way = DONE

👾 

MK’s original message:

the current styling for profile pics works for landscape images, but not portrait images. They'll end up being too long:
http://g.recordit.co/wPBKWFvTEa.gif

i think the answer may be determining if it's portrait or landscape & setting styles based on that: http://stackoverflow.com/questions/13518833/making-all-photos-square-via-css

**Comment by ackernaut** [comment] 2017-01-05 19:40
Oh, I thought we were thinking of adding a simple crop tool to the “update user photo” workflow? If we force the crop to have square dimensions, then we solve our problem, no? I guess if we pulled images from other sources (possible with auth0?) they may not be squares? Then we have this problem again?

**Comment by ackernaut** [comment] 2017-01-05 19:40
But hey if we can tell the orientation and have conditional styles, I'm def. willing to explore that!!

**Comment by jordanh** [comment] 2017-01-11 14:23
This is forcing the profile image to be square.

Estimated effort: 1 point

**Comment by jordanh** [comment] 2017-02-14 00:00
Duplicate of two new issues.

**Closed by jordanh** 2017-02-14 00:00 UTC
Labels: bug
