### ISSUE TITLE
Navigating between teams fails

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#3502] opened 2020-01-23 17:42 UTC
## Issue - Bug

Ever since v4.17.0, I've been seeing a new behavior.

Reproduction steps:
1. Login Parabol, navigate to a team dash
2. Leave it alone
3. After as few as 5 minutes of the tab sitting idle, switch to a different team dash or My Dashboard
4. Note that new location will not load (you get a forever spinner or a blank div)

If you refresh, you're able to load the target route.

- **OS:** macOS
- **Browser:** Chrome 79
- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - resume Parabol sessions and navigate from a team dash to another route without refreshing

**Comment by ackernaut** [comment] 2020-01-23 18:04
Possibly related: #3498

**Comment by jordanh** [comment] 2020-01-23 18:08
[A customer](https://app.hubspot.com/contacts/3888472/contact/3827001) 🔒 writes:

> i clicked on timeline in dashboard and it is clocking...can you send me the export of our 65 or so note sheets, thanks

**Comment by mattkrick** [comment] 2020-01-23 19:47
could not reproduce, here were my steps:
1. log in to prod, go to team dash, hit refresh
2. wait 6 minutes, browse the web in another tab
3. click my dashboard, it loads

does the computer need to sleep? should the tab stay active? does it only happen from login w/o a refresh in the middle?

**Comment by mattkrick** [comment] 2020-02-01 18:37
v4.17.0 added logic for blacklisted JWTs, but also introduced a bug in the reconnection logic. 
if the app doesn't reconnect, then it's essentially an offline app, which would explain why navigating would show a spinner & only optimistic updates would occur. 
this is fixed in trebuchet-client@1.2.0

**Closed** 2020-02-03 22:26 UTC
Labels: bug
