### ISSUE TITLE
TypeError: Cannot read property 'getBlockMap' of undefined (archive broken?)

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1280] opened 2017-08-19 17:10 UTC
https://sentry.io/parabol/action-production/issues/329603473/

```
TypeError: Cannot read property 'getBlockMap' of undefined
  at getBlockMap (../node_modules/draft-js/lib/EditorState.js:56)
  at createWithContent (./universal/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.js:41:31)
  at u._constructComponentWithoutOwner (../node_modules/react-dom/lib/ReactCompositeComponent.js:297)
  at _constructComponentWithoutOwner (../node_modules/react-dom/lib/ReactCompositeComponent.js:284)
  at _constructComponent (../node_modules/react-dom/lib/ReactCompositeComponent.js:187)
...
(45 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment] 2017-08-19 17:28
Adam P ran into this one

1. After archiving a bunch of cards on his team board
2. Navigated to the archive, so no archived cards
3. Observed this exception

Team id: `BJN5Fk8u-`

**Comment by mattkrick** [comment] 2017-08-20 21:41
dupe of #1270. let's get what we already got of this PR merged on monday.

**Closed by mattkrick** 2017-08-20 21:41 UTC
