### ISSUE TITLE
past Due Date color coding bug

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#2208] opened 2018-06-14 15:45 UTC
## Issue - Bug

Today's date is June 14: all past due date colors are correct, except the June 13 (should be red as it is past due). 

There were several more, unfortunately I'd adjusted the Due Dates before I realized it. NOTE: the cards that had been "due" June 12 were red (correct)

![due dates](https://user-images.githubusercontent.com/14892189/41423050-581c8e08-6fc8-11e8-8c1f-0a71acafdb26.jpg)

- **OS:** macOS / Linux / Windows / ?
- **Browser:** Chrome / Safari / Lynx / ? + version
- **Node version:** `node --version`
- **NPM version:** `npm --version`
- **RethinkDB version:** `rethinkdb --version`
- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment] 2018-06-14 17:40
@tayamueller if you hover over a card with the incorrect color, does the color update? if so, may be related to #2124

Also, this is a duplicate of #2140

**Comment by jordanh** [comment] 2018-06-20 15:05
Closing as a dupicate

**Closed by jordanh** 2018-06-20 15:05 UTC
Labels: bug, duplicate
