### ISSUE TITLE
Promote myself to Facilitator is broken (no mutation sent) in Retro Meeting

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2831] opened 2019-04-26 18:54 UTC
AC:
   - When in retro meeting, can promote myself to facilitator​

EE: 10.5 points

**Comment by jordanh** [comment] 2019-06-04 17:33
Scrubbed. Added AC & EE. Added to project, added label and milestone.

**Comment by jordanh** [comment] 2019-06-11 17:11
@mattkrick sez, "I can't reproduce." Closing for now.

**Closed by jordanh** 2019-06-11 17:11 UTC
Labels: enhancement
