### ISSUE TITLE
Check for errors sending invites from team settings

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2114] opened 2018-05-08 21:17 UTC
## Bug
This may just be a local issue, perhaps related to HMR.
1) Go to team settings
2) Invite another user
3) Look for errors like:
```
Uncaught TypeError: Cannot read property 'getDataID' of undefined
    at addNodeToArray (addNodeToArray.js:50)
    at handleAddSoftTeamMember (handleAddSoftTeamMembers.js:25)
    at eval (pluralizeHandler.js:16)
    at inviteTeamMembersTeamMemberUpdater (InviteTeamMembersMutation.js:278)
    at updater (TeamMemberSubscription.js:53)
    at RelayPublishQueue._getSourceFromPayload (RelayPublishQueue.js:170)
    at eval (RelayPublishQueue.js:184)
    at Set.forEach (<anonymous>)
    at RelayPublishQueue._commitData (RelayPublishQueue.js:181)
    at RelayPublishQueue.run (RelayPublishQueue.js:143)
```
### AC
- Verify if error exists beyond the local env.
- Fix if within 10.5 points of effort, otherwise update the issue or write a new one
- The Team Settings view updates completely when there are changes (see #2118)
### EE
- 10.5 points

**Comment by mattkrick** [comment] 2018-05-23 01:28
could not reproduce, closing for now

**Closed by mattkrick** 2018-05-23 01:28 UTC
Labels: bug, groomed
