### ISSUE TITLE
GitHub Integrated Card: Assignee Problems

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1235] opened 2017-08-10 14:04 UTC
Few questions that need to be answered before moving forward. High priority because these answers are blocking progress on the current sprint. Answers can be long-term goals (for example, we could make assignees "subscribers", but then again, issues already let you subscribe...)

Creating on github:
- What happens when an issue is created on GitHub with no assignees? What will we do with it?
- What happens when an issue is created on GitHub with > 1 assignee?
- What happens when an issue is created on GitHub with an assignee that isn't integrated?

Updating on github (Consider that they could be temporary while switching assignees):
- What happens when an issue that had an [integrated, unintegrated] assignee gets the only assignee removed? 
- What happens when an issue that had an [integrated, unintegrated, no] assignee gets an unintegrated assignee added?
- What happens when an issue that had an [integrated, unintegrated, no] assignee gets an integrated assignee added?

@jordanh @ackernaut

**Comment by mattkrick** [comment] 2017-08-11 22:56
@jordanh please review:

Creating on github:
- What happens when an issue is created on GitHub with no assignees? What will we do with it?
  - We ignore it. it doesn't exist to us.
- What happens when an issue is created on GitHub with > 1 assignee?
  - choose the first integrated assignee. ignore the rest
- What happens when an issue is created on GitHub with an assignee that isn't integrated?
  - ignore it.
Updating on github (Consider that they could be temporary while switching assignees):
- What happens when an issue that had an [integrated, unintegrated] assignee gets the only assignee removed? 
  - integrated: archive it & keep the current owner
  - unintegrated: noop, we would've ignored it
- What happens when an issue that had an [integrated, unintegrated, no] assignee gets an unintegrated assignee added?
  - ignore
- What happens when an issue that had an [integrated, unintegrated, no] assignee gets an integrated assignee added?
  - integrated: ignore
  - unintegrated: create the issue or bring it back from the archives
  - no: create the issue

**Comment by jordanh** [comment] 2017-08-11 23:13
My thoughts below:

Note for below 'near' may mean 'first when we can', not now. 'far' means maybe sometime in the future.

Creating on github:
- What happens when an issue is created on GitHub with no assignees? What will we do with it?
   - near: we ignore, far: we make it configurable to assign to a specific fallback person (we're a bot!)
- What happens when an issue is created on GitHub with > 1 assignee?
  - yeah, choose the first
- What happens when an issue is created on GitHub with an assignee that isn't integrated?
   - near: we ignore, far: in some UI somewhere, we show a list of folks to consider inviting to the team

Updating on github (Consider that they could be temporary while switching assignees):
- What happens when an issue that had an [integrated, unintegrated] assignee gets the only assignee removed? 
  - integrated: archive it & keep the current owner
  - unintegrated: near is noop, we would've ignored it; far is reverts to configured fallback owner

- What happens when an issue that had an [integrated, unintegrated, no] assignee gets an unintegrated assignee added?
   - near: we ignore, far: ui element that suggests who else you might want to invite to the team

- What happens when an issue that had an [integrated, unintegrated, no] assignee gets an integrated assignee added?
   - integrated: if swapped one for one, assign to new integrated assignee (potentially bringing it back from the archives)
   - unintegrated: create the Project or bring it back from the archives
   - no: create the issue as a Project card

**Comment by mattkrick** [comment] 2017-08-13 00:28
@jordanh 
> integrated: if swapped one for one, assign to new integrated assignee (potentially bringing it back from the archives)

there's no swaps, only add & remove. to perform a swap in github, you either add a new assignee & then remove the old one, or remove the old one, then assign the new. this makes it challenging because if you assign the new one first, then we will ignore that call. then, when you remove the old one, we need to call github again to see if there assignees left to become the owner.

alternatively, we could make the new assignee the new owner. that would eliminate a call to GH if they are trying to swap owners, but could be bad if they assign to someone & don't want to switch owners.

alternatively still, we could keep a list of "assignees" in our DB for each issue, but i don't like this because that's 1 more thing to keep track of. eventually, we'll need to handle people changing their github usernames, and that'll make it much more expensive.

**Comment by mattkrick** [comment] 2017-08-13 00:38
another consideration: bringing a card from out of the archive isn't always what they want. For example, let's say i finished a project. then, someone goes back to that closed issue & adds an assignee. sure, we should change the owner in parabol. but should we take the #archive tag off of it? the thing was already finished. Maybe a good-enough heuristic is to bring it back from the archive if the status is NOT "Done"?

**Comment by jordanh** [comment] 2017-08-13 16:09
These are good points. Ok, so:

My thoughts below:

Note for below 'near' may mean 'first when we can', not now. 'far' means maybe sometime in the future.

Creating on github:
- What happens when an issue is created on GitHub with no assignees? What will we do with it?
   - near: we ignore, far: we make it configurable to assign to a specific fallback person (we're a bot!)
- What happens when an issue is created on GitHub with > 1 assignee?
  - yeah, choose the first
- What happens when an issue is created on GitHub with an assignee that isn't integrated?
   - near: we ignore, far: in some UI somewhere, we show a list of folks to consider inviting to the team

Updating on github (Consider that they could be temporary while switching assignees):
- What happens when an issue that had an [integrated, unintegrated] assignee gets the only assignee removed? 
  - integrated: archive it & keep the current owner
  - unintegrated: near is noop, we would've ignored it; far is reverts to configured fallback owner

- What happens when an issue that had an [integrated, unintegrated, no] assignee gets an unintegrated assignee added?
   - near: we ignore, far: ui element that suggests who else you might want to invite to the team

- What happens when an issue that had an [integrated, unintegrated, no] assignee gets an integrated assignee added?
   - integrated: ignore
   - unintegrated: create the Project or bring it back from the archives
   - no: create the issue as a Project card

**Comment by jordanh** [comment] 2017-08-13 16:43
We should most definitely write up a high-level document that shows the mapping of our states to GitHub states and vice-versa. Ideally, it would be a pair of tables (CRUDs Parabol -> GitHub, CRUDs GitHub -> Parabol) we could reuse for many kinds of integrations.

> another consideration: bringing a card from out of the archive isn't always what they want. For example, let's say i finished a project. then, someone goes back to that closed issue & adds an assignee. sure, we should change the owner in parabol. but should we take the #archive tag off of it? the thing was already finished. Maybe a good-enough heuristic is to bring it back from the archive if the status is NOT "Done"?

Yeah, I was just plain wrong here.

Thinking about cases, I think we could get ourselves into a lot of trouble mapping our two states (Done and #archived) to GitHub (and other services) states and vice-versa. Consider the below case for an unintegrated assignee getting an integrated assignee added:

> - What happens when an issue that had an [integrated, unintegrated, no] assignee gets an integrated assignee added?
>   - integrated: ignore
>   - **unintegrated: create the Project or bring it back from the archives**
>   - no: create the issue as a Project card

Doing the right thing by the user is going to depend on the state of the GitHub issue. If the issue is marked as closed on GitHub we should probably leave it in our archive. If the GitHub issue is open, then we'll want to surface it and map it to the appropriate state (Inbox/Stuck/Active/Done) according to our GitHub integration label mapping rules.

So we might just spec for this case:

> - What happens when an issue that had an [integrated, unintegrated, no] assignee gets an integrated assignee added?
>   - integrated: ignore
>   - **unintegrated: create or update the Project**
>   - no: create the issue as a Project card

As a general design principle, I think we should endeavor to be _very_ simple in the near-term and try to translate states in the simplest possible fashion, backlogging any helpful heuristics as future configurable integration options.

**Closed** 2018-03-01 03:34 UTC
Labels: discussion
