### ISSUE TITLE
copy/paste links from one card to another

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1473] opened 2017-11-07 19:34 UTC
## Issue - Enhancement

When I copy linked info from one card to another, I want the link to be pasted (currently reverts to plain text)

current usage: 
- switching cards from one team to another
- duplicating 1 card for multiple teammates
(1st instance could be solved in future by creating method to change team on card w/out c/p)

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tayamueller** [comment] 2017-11-07 19:38
#1474

**Comment by jordanh** [comment] 2017-12-06 17:25
Duplicate of #1537

**Closed** 2017-12-06 17:25 UTC
