### ISSUE TITLE
Archive squeeze bug and improvements

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2081] opened 2018-05-02 17:35 UTC
## Enhancement

I’m not sure if we want to show the squeeze on a new team if they haven’t reach the 14-day limit and/or do not have any archived cards. I’m confused by this state:

![screenshot 2018-05-02 12 26 33](https://user-images.githubusercontent.com/307286/39539027-3af07ce4-4e04-11e8-9ead-30f3660862c7.png)

Repro steps:
- Create a new team
- Archive a task
- Unarchive the task
- Archive and unarchive it again
- The squeeze is there saying 1 card is unavailable

### Acceptance Criteria
- The business logic is clear and information is accurate when we show the archive squeeze
- Polish the styles of the presentation 

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment] 2018-10-17 23:11
Duplicate of #2204

**Closed by jordanh** 2018-10-17 23:11 UTC
Labels: bug, enhancement
