### ISSUE TITLE
properly support failed invitations

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1345] opened 2017-09-14 23:35 UTC
here's the broken invitation flow:
- get email, click url
- goto parabol page, login modal pops up, create new account, submit
- the inviteToken comes back expired, now i just see ducks
- if i go back to action.parabol.co, it will take me to the `/me` page because i'm logged in, but i'm not on any teams!

i can build whatever we wanna do, just not sure what to do :-)

**Comment by jordanh** [comment] 2017-09-15 07:33
I think the flow here could be described by this JTBD:

When I accept an expired invitation, I want to get a message telling me that the invitation is expired but I still want to be able to onboard myself to Parabol, so that I don't feel left out and might be able to take some next action.

In other words, I think we just pop them a toast/modal and redirect them to the welcome wizard. Optionally we could send them a notification with a mailto: link to person that invited them (so they can be pestered for a new invitation)...but I think that might be going too far.

**Comment by ackernaut** [comment] 2017-09-26 16:14
duplicate of #1356

**Closed** 2017-09-26 16:14 UTC
Labels: design
