### ISSUE TITLE
Meeting guest pass

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#689] opened 2017-02-02 16:58 UTC
## Enhancement

When a team feels the need to include somebody (not on the team, not part of the org) in a meeting, they want a guest invite (link, email) that they can send so that that person can join 1 time (then the invite is invalid).

Team members can only invite one person at a time (an invite cannot be sent to multiple emails, an invite link cannot be used by multiple people). The invite is only good for one meeting.

Team can invite up to X guests in any given meeting.

A person can be invited to multiple meetings, but with a new invite.

We follow up with a nudge, “would you like to add this person to the team” for each guest?

- **Estimated effort**: 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment] 2018-03-27 17:52
Duplicate of #1078

**Closed by jordanh** 2018-03-27 17:52 UTC
Labels: design, enhancement, idea
