### ISSUE TITLE
Meeting agenda processing order bugs

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1156] opened 2017-07-21 01:34 UTC
## Issue - Bug

While running our 25-agenda item, ExCo meeting today we ran into some odd bugs. Roughly, these are the behaviors we saw:

1. Unable to delete item #2
2. When processing the agenda list, the facilitators display would advance to the next item and the _subsequent_ (unprocessed) item would be marked as a completed
3. Intermittently, when advancing to the next item the above would happen _and_ the current item would move itself to become item #2 in the agenda list
4. The user(s) would become unsynchronized from the facilitator

![ab](https://user-images.githubusercontent.com/103000/28445567-eb9b248e-6d79-11e7-986c-d61b6c8701b6.gif)

Capturing this now to see if the cause might be known (were there recent changes pushed to production?), or, if it is reproducible and we catch it during our next meeting.

**Comment by ackernaut** [comment] 2017-07-21 03:36
This feels like a regression…like we already fixed this once before. But not the most helpful comment, I know!

**Comment by mattkrick** [comment] 2017-08-24 22:22
how is it possible that you got past item # 1 without completing it? The rest of the stuff is expected, per the business logic, you must complete items in order. therefore, the next item you complete _must_ be the following.

same as #1158 there's not too much i can do without seeing the Team doc from the DB or maybe any server logs. Until then, i'll assume moving to relay will fix this because by using optimistic updates, the UI will always match the DB state, eliminating latency as a posssible cause.

**Closed by mattkrick** 2017-08-24 22:22 UTC
Labels: bug, can't reproduce
