### ISSUE TITLE
duplicate cards & active meeting bug/s

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1775] opened 2018-02-19 22:05 UTC
## Issue - Bug

1) This didn't occur immediately - I took a screenshot to share with Parabol immediately after the meeting this AM and it wasn't there then:
![pros](https://user-images.githubusercontent.com/14892189/36398658-325b42b8-1596-11e8-926d-4c3f11bf2dc7.jpeg)
2) Went for lunch, came back & 2hrs later this is the view: (I didn't touch the board or start a meeting)
![gld bugs](https://user-images.githubusercontent.com/14892189/36398560-af04418a-1595-11e8-9fa1-ffc42edd9634.jpeg)
3) Note doubles & triples of each agenda item
4) The doubles (mailing addresses, Peter, and new post) were created DURING the previous meeting and should have been cleared after processing (and weren't visible in above screenshot)
5) The lone triple (new feature request updates) was created AFTER the meeting, to be processed in the next meeting. Not sure why it's showing up in the middle.
6) 3 of 5 participants created Agenda items during the mtg but only my old ones are visible.
7) Note orange WebSockets notification, which went away. There WAS ALSO another notification that "You're not online" which I didn't capture in time in this screenshot.
8) Probably related to #1771 ?

### Acceptance Criteria (optional)
Users can:
   - Do this
   - Do that
   - Cannot do that

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment] 2018-02-20 05:38
using this issue for notes:

currently, the client can't detect if it's connected to the server.
socket cluster did this by sending a ping/pong on both the server & client
- apollo only receives a ping, it doesn't send out a pong. that means the server doesn't know when there is a disconnect & could result in a memory leak.
- apollo also has an `unsentMessageQueue`which avoid race conditions between the socket opening & the messages being sent
- reverting back to what socket cluster does is probably the best thing to do. However, we still have a problem-- we have reconnect logic, which socket cluster didn't. this is generally helpful, but we need the client to close the connection ASAP because the client will resend anything that didn't go through on the last connection. since our mutations are idempotent, that means we could still end up in the same place as today.
- a 10 second ping is OK for now, but in the future, we'll probably want to attach a time limit to the messages sent out. then, we can establish a latency & do something like "if we've waited 3x longer than the average latency, then close the websocket". this will be helpful in closing the socket efficiently.
- bug 2: we were creating a pending subscription on the server before closing out the possibly existing old one. this has nothing to do with the above error, but it would allow a nefarious client to cause a very minor memory leak if they knew what to do
- bug 3: we onmessage listeners on the server were waiting behind a gql connection query. this was no good for reconnects, since the messages would get sent to the server, but wouldn't be heard.
 - NOTE: the above 3 bugs do NOT fix the problem. 
- bug 4: The real problem is caused by the unsentMessageQueue in apollo that is storing every mutation and query, not just subscriptions. this is because in apollo land, everything handled by the subscription transport becomes an observable. That means when you trigger a mutation (GQL_START) you need to wait for the data (GQL_DATA) and an additional GQL_COMPLETE frame to know it's done. it's a freakin mutation, you're only gonna get 1. that's a whole lot of unnecessary complexity just for the sake of being cute. to fix this, i stopped using apollo's `request` and wrote my own.

**Closed** 2018-02-20 05:47 UTC
Labels: pr review
