### ISSUE TITLE
can't proceed on create team page

### ISSUE THREAD

**Issue by cometta** [ParabolInc/action#202] opened 2016-08-19 00:41 UTC
I get below error and unable to proceed on the 'create team' page right after entered team member wizard page.

DEBUG GraphQL Error: [ { Bad Request: Bad HTTP authentication header format
      (No stack trace)
  From previous event:
      at Client.request (/userx/action/node_modules/rest-facade/src/Client.js:250:17)
      at Client.patch (/userx/action/node_modules/rest-facade/src/Client.js:150:15)
      at UsersManager.updateAppMetadata (/userx/action/node_modules/auth0/src/management/UsersManager.js:252:21)
      at _callee5$ (teamMutation.js:188:37)
      at tryCatch (/userx/action/node_modules/regenerator-runtime/runtime.js:62:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (/userx/action/node_modules/regenerator-runtime/runtime.js:336:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/userx/action/node_modules/regenerator-runtime/runtime.js:95:21)
      at step (teamMutation.js:16:1)
      at teamMutation.js:16:1
      at new Promise (/userx/action/node_modules/core-js/modules/es6.promise.js:191:7)
      at teamMutation.js:16:1
      at resolve (teamMutation.js:166:51)
      at resolveOrError (/userx/action/node_modules/graphql/execution/execute.js:447:12)
      at resolveField (/userx/action/node_modules/graphql/execution/execute.js:438:16)
      at /userx/action/node_modules/graphql/execution/execute.js:219:20
      at run (/userx/action/node_modules/core-js/modules/es6.promise.js:87:22)
      at /userx/action/node_modules/core-js/modules/es6.promise.js:100:28
      at flush (/userx/action/node_modules/core-js/modules/_microtask.js:18:9)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
    message: 'Bad HTTP authentication header format',
    locations: [Getter],
    path: [ 'createTeam' ] } ]

**Comment by jordanh** [comment] 2016-08-19 01:33
Thank you for reporting this. We just merged our latest sprint `meeting-update` and this might be a regression.

I tested myself and couldn't proceed past team invitations with the following stack trace, so something is up:

```
DEBUG GraphQL Error: [ { Error: {"_error":"Unauthorized to view team details."}
      at errorObj (utils.js:5:32)
      at requireSUOrTeamMember (authorization.js:31:13)
      at _callee$ (invitationMutation.js:34:7)
      at tryCatch (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:62:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:336:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:95:21)
      at step (invitationMutation.js:12:1)
      at invitationMutation.js:12:1
      at new Promise (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/core-js/modules/es6.promise.js:191:7)
      at invitationMutation.js:12:1
      at resolve (invitationMutation.js:33:60)
      at resolveOrError (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:447:12)
      at resolveField (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:438:16)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:219:20
      at run (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/core-js/modules/es6.promise.js:87:22)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/core-js/modules/es6.promise.js:100:28
      at flush (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/core-js/modules/_microtask.js:18:9)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
    message: '{"_error":"Unauthorized to view team details."}',
    locations: [Getter],
    path: [ 'inviteTeamMembers' ] } ]
```

@cometta would you mind taking a screenshot of what the UI looked like when you saw this? I'd like to make sure we're seeing the same thing...

**Comment by jordanh** [comment] 2016-08-19 01:50
Oh, I'm pretty sure this isn't good:

![image](https://cloud.githubusercontent.com/assets/103000/17796348/c3beb970-658d-11e6-9dab-cf9fc4e57043.png)

**Comment by cometta** [comment] 2016-08-19 12:40
@jordanh  , image as requested. 
![action_bug](https://cloud.githubusercontent.com/assets/187495/17810030/2e3627ce-664d-11e6-86a4-2c4cf58d4c3a.jpg)

**Comment by jordanh** [comment] 2016-08-19 12:50
@cometta, thank you! Good, we're seeing the same thing at the same place.

@mattkrick and I were looking at this last night – we know what's going on. Behind the scenes when you create a new team, we update the user's JWT authentication token to contain the new team memberships. We rather recently performed this refactoring. (this fat token let's us authorize pub/sub operations quickly in later parts of the app).

Turns out we didn't come back and retest the `/welcome` journey. It looks like there is a race. We update this token asynchronously and the subsequent invitation step is still using the old token. We'll get this fixed right up.

@mattkrick let's put this bugfix on a branch. I'd like to remove the mailgun project requirement and print "would have sent mail to..." in at the same time.

**Comment by jordanh** [comment] 2016-08-22 15:35
@cometta we've got this all fixed up as part of a larger code refactor we just merged in #206. It'll require a new release of [Cashay](https://github.com/mattkrick/cashay). Stand by, we'll get that out soon!

Thank you again for reporting this.

**Comment by cometta** [comment] 2016-08-31 13:24
```
@jordanh , I still get error after upgraded action and cashay.   

DEBUG GraphQL Error: [ { Client is not global
    message: 'Client is not global',
    locations: [Getter],
    path: [ 'createTeam' ] } ]


```

TeamMutation.js -> createTeam -> does not get pass   await Promise.all(dbPromises);
Step2TeamName.js-> cashay.mutate('createTeam', createTeamOptions).then((res)  -->
dispatch(setAuthToken(res.data.createTeam)); //this line has issue

**Comment by jordanh** [comment] 2016-08-31 13:26
Interesting. That's stinky.

You're on the latest master?

**Comment by cometta** [comment] 2016-08-31 13:30
yes latest from 'master' and using cashay 0.19

**Comment by cometta** [comment] 2016-08-31 13:31
in browser :  

Object {createTeam: null}
createTeam
:
null
__proto__
:
Objec

**Comment by jordanh** [comment] 2016-08-31 13:32
How interesting (and embarrassing), I'll look at this right now.

**Comment by jordanh** [comment] 2016-08-31 13:49
Hmm. I'm not able to reproduce that here. Could you tell us what your browser environment looks like?

- **OS:** OSX / Linux / Windows / ?
- **Browser:** Chrome / Safari / Lynx / ? + version
- **Node version:** `node --version`
- **NPM version:** `npm --version`
- **RethinkDB version:** `rethinkdb --version`
- **Estimated effort:** X points ([see CONTRIBUTING.md]

Do you have [redux-devtools](https://github.com/gaearon/redux-devtools) installed? We'd also love a copy of your redux state...

**Comment by jordanh** [comment] 2016-08-31 14:00
...and one more thing if you don't mind. Could you try copying `.env.example` to `.env` and retesting? I have a hunch...

**Comment by cometta** [comment] 2016-08-31 23:23
OS: OSX 
    Browser: Chrome 52.0.2743.116 (64-bit) + Firefox 48.0.1
    Node version: node 6.3.1
    NPM version: npm 3.10.5
    RethinkDB version: rethinkdb 2.3.2 (CLANG 7.3.0 (clang-703.0.29))
    Estimated effort: X points ([see CONTRIBUTING.md]

i try post redux-devtools state later

**Comment by jordanh** [comment] 2016-09-01 04:52
Although the chances were slim, I updated my node to 6.4.0. Still was able to proceed through the welcome wizard without reproducing what you're seeing. Bummer.

I'm somewhat relieved that my "hunch" around `.env` proved to be incorrect.

One last thing I can think of to try before we start to really go deep is, using Chrome, could you:

1. Open dev tools
2. Load http://localhost:3000 (the Action app)
3. Click Application -> Local Storage
4. Delete all of the keys appearing there

Then, retest.

As I was thinking through potential causes, I came up with one that sounded plausible. (Note: I'm making some assumptions...):

- You pulled the latest changes
- Ran `npm run dev` and tested and the wizard still didn't work *then*
- Ran `npm install` which upgraded Cashay et al
- And retested

If you did something like this, the older version of Cashay may have stuck things in our cached redux storage in a slightly different way than the newer version of Cashay. We only detect and invalidate this cache when the version of the app changes. You'd see some spooky errors.

If it's not this...I'll have to think harder 😉

**Comment by cometta** [comment] 2016-09-01 05:05
@jordanh  , ok i will try the steps and update here. by the way. I did the latest master from git using zip. probably our source files are different. I run with npm run start

**Comment by cometta** [comment] 2016-09-01 10:33
@jordanh, I clear chrome localstorage and retested. Now i'm forwarded directly to dashboard once I'm logged in. When i click 'add new team' on the left menu nothing happen.  i try go to /welcome and go through wizard, still stuck on same page

**Comment by jordanh** [comment] 2016-09-01 12:59
Ah ha! That was the key info – you were using `npm run start`. Found it!

Our .env.example contained an incorrect development token. It should work now.

To retest:

1. pull down the latest master
2. `cp .env.example .env`
3. `npm run build`
4. `npm run start`

Then it should work just fine...

**Comment by cometta** [comment] 2016-09-01 13:25
@jordanh  you hit the bulleye =) yes it is working now for the wizard.   Just to let you know the dashboard left menu  'add new team' button is not working.

**Comment by jordanh** [comment] 2016-09-01 13:28
Great! Very happy to hear. I'll close this issue.

On the "Add New Team": we haven't implemented that yet :)

This is where we're at on our current epic development: https://github.com/ParabolInc/action/blob/d7af00247c7b095e6b68f76d995701422771d3e3/docs/epics/0001_Action_Epic_MVTP.md

Adding new teams is coming soon!

**Closed by jordanh** 2016-09-01 13:28 UTC
Labels: bug
